insert into books (author,title,copies,code) values ('Mariona Nadal','Curso de programacion en java', 5, 'INF0001')
insert into books (author,title,copies,code) values ('George Dyson','La catedral del tuning', 5,'INF0002')
insert into books (author,title,copies,code) values ('Robert C. Martin','Codigo limpio ', 5,'INF0003')
insert into books (author,title,copies,code) values ('Andy Hunt','El programador pragmatico', 1,'INF0004')
insert into books (author,title,copies,code) values ('Carlos Alberto Cortijo Bon', 'Programación de servicios y procesos',5,'INF0005')

insert into students (dni,email,is_active,name,phone) values ('13.824.785-6','gvidalhernandez@gmail.com',true,'Gustavo Vidal Hernández','+56 9 4287 4817')
insert into students (dni,email,is_active,name,phone) values ('19.786.776-9','jperezgallardo@gmail.com',true,'Juan Pérez Gallardo','+56 9 4455 3322')
insert into students (dni,email,is_active,name,phone) values ('13.978.211-5','z_carlos.ramirez@gmail.com',true,'Carlos Ramirez Zapata','+56 9 2234 9978')
insert into students (dni,email,is_active,name,phone) values ('19.962.970-0','avidal.hernandez@gmail.com',false,'Roberto Vidal Hernandez','+56 9 4532 9987')